POST http://localhost:8000/register HTTP/1.1
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john@gmail.com",
    "password": "securepassword123",
    "username": "johndoe"
}

###


POST http://localhost:8000/login HTTP/1.1
Content-Type: application/json

{
    "email": "john@gmail.com",
    "password": "securepassword123"
}
